version: "3" 
services:

    web:
        image: nginx
        ports:
          - "5000:80"
        links:
          - fpm
        volumes:
          - "./src/nginx/:/etc/nginx/conf.d/"
    fpm:
        image: php:7.4-fpm
        tty: true
        volumes:
          - "./src/php/:/var/www/html/"
       
        